# Generated by Django 5.0.7 on 2024-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_prestador'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='confirmado_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
