# Generated by Django 5.0.7 on 2024-09-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_estadosagendamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadosAgendamento',
        ),
    ]
