# Generated by Django 5.0.7 on 2024-09-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_cliente_fidelidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidelidade',
            name='agendamento_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento'),
            preserve_default=False,
        ),
    ]
