# Generated by Django 5.0.7 on 2024-12-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_fidelidade_agendamento_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
                ('localidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestador_endereco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
