# Generated by Django 5.0.7 on 2024-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendamento_confirmado_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=100)),
            ],
        ),
    ]
