# Generated by Django 5.0.7 on 2024-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_delete_estadosagendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cancelamento_agendamento',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='confirmado_agendamento',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='estado_agendamento',
            field=models.CharField(choices=[('AG', 'agendado'), ('CO', 'confirmado'), ('CA', 'cancelado'), ('EX', 'executado')], default='AG', max_length=2),
        ),
    ]
